// Mutation source-to-spec classification, shared by the Stryker runner and scope guard.
export const MUTATE_SPECS: Record<string, string[]> = {
	'src/ingest/parse/anthropic.ts': ['test/parse-anthropic.test.ts'],
	'src/lib/article-url.ts': ['test/article-url.test.ts'],
	'src/ingest/parse/lab-html.ts': ['test/lab-html.test.ts'],
	'src/ingest/parse/ai-labs.ts': ['test/parse-ai-labs.test.ts'],
	'src/ingest/parse/extropic.ts': ['test/parse-extropic.test.ts'],
	'src/ingest/ai-lab-sources.ts': ['test/ai-lab-sources.test.ts'],
	'src/ingest/parse/inception.ts': ['test/parse-inception.test.ts'],
	'src/ingest/bounded-fetch.ts': ['test/bounded-fetch.test.ts'],
	'src/lib/feed-health.ts': ['test/feed-health.test.ts'],
	'src/lib/auth.ts': ['test/auth-validate.test.ts', 'test/auth-validate.prop.test.ts'],
	'src/lib/digest.ts': ['test/digest.test.ts', 'test/digest.prop.test.ts'],
	'src/ingest/schedule.ts': ['test/schedule.test.ts', 'test/schedule.prop.test.ts'],
	'src/ingest/merge.ts': ['test/merge.test.ts', 'test/merge.prop.test.ts'],
	'src/ingest/queries.ts': ['test/queries.test.ts'],
	'src/lib/deploy.ts': ['test/deploy.test.ts'],
	'src/lib/pagination.ts': ['test/pagination.test.ts'],
	'src/lib/return-path.ts': ['test/return-path.test.ts'],
	'src/lib/log.ts': ['test/log.test.ts'],
	'src/lib/email.ts': ['test/email.test.ts'],
	'src/lib/sources.ts': ['test/source-meta.test.ts'],
	'src/ingest/validate.ts': ['test/validate.test.ts'],
	'src/ingest/sources.ts': ['test/sources.test.ts'],
	'src/ingest/parse/intel-newsroom.ts': ['test/parse-intel-newsroom.test.ts'],
	'src/ingest/parse/deepseek-updates.ts': ['test/parse-deepseek-updates.test.ts'],
	'src/ingest/fetch/owenomics.ts': ['test/fetch-owenomics.test.ts'],
	'src/ingest/parse/atom.ts': ['test/parse-atom.test.ts'],
	'src/ingest/parse/rss20.ts': ['test/parse-rss20.test.ts'],
	'src/ingest/parse/aws-whats-new.ts': ['test/parse-aws-whats-new.test.ts'],
	'src/ingest/parse/sec-edgar.ts': ['test/parse-sec-edgar.test.ts'],
	'src/ingest/parse/ti-newsroom.ts': ['test/parse-ti-newsroom.test.ts'],
	'src/ingest/parse/thinking-machines-news.ts': ['test/parse-thinking-machines-news.test.ts'],
	'src/ingest/parse/meta-ai.ts': ['test/parse-meta-ai.test.ts'],
	'src/ingest/parse/jpm-eotm.ts': ['test/parse-jpm-eotm.test.ts'],
	'src/ingest/parse/owenomics.ts': ['test/parse-owenomics.test.ts'],
	'src/ingest/parse/cursor.ts': ['test/parse-cursor.test.ts'],
	'src/ingest/parse/entities.ts': ['test/parse-entities.test.ts'],
	'src/ingest/parse/count.ts': ['test/count.test.ts'],
	'src/ingest/parse/dates.ts': ['test/dates.test.ts'],
};

export const MUTATION_TESTS = [...new Set(Object.values(MUTATE_SPECS).flat())];
