import { test, expect } from './fixtures';
import { d1Query } from './d1';
import { SOURCES } from '../src/ingest/sources';
// Red -> green: the previous static /status shows no owner ingestion state.
// Exercise the real middleware/session/cache boundary and current D1 records.
const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
test.use({ viewport: { width: 390, height: 844 } });
test.beforeEach(() => {
	const now = Math.floor(Date.now() / 1000);
	d1Query(`INSERT INTO feeds(feed,source,next_poll_at,last_status) VALUES ${SOURCES.map(config => `(${quote(config.feed)},${quote(config.source)},${now + 3600},200)`).join(',')}`);
	d1Query(`INSERT INTO feed_health(feed,last_attempt_at,last_finished_at,response_status,last_success_at,last_clean_at) SELECT feed,${now - 100},${now - 90},200,${now - 90},${now - 90} FROM feeds`);
	const sources = [...new Set(SOURCES.map(config => config.source))];
	d1Query(`INSERT INTO items(source,guid,url,title,published_at,fetched_at) VALUES ${sources.map((source, i) => `(${quote(source)},'health-${i}','https://example.com/health-${i}','A recent source article',${now - 600},${now - 500})`).join(',')}`);
	d1Query(`UPDATE feeds SET failure_count=3 WHERE source='openai'`);
	d1Query(`UPDATE feed_health SET response_status=503,last_error='upstream-private-marker',last_error_at=${now - 90},error_resolved_at=NULL WHERE feed IN (SELECT feed FROM feeds WHERE source='openai')`);
	d1Query(`UPDATE feed_health SET last_anomaly='Parsed zero of twelve entries',last_anomaly_at=${now - 90},anomaly_resolved_at=NULL WHERE feed IN (SELECT feed FROM feeds WHERE source='meta-ai')`);
	d1Query(`DELETE FROM feed_health WHERE feed IN (SELECT feed FROM feeds WHERE source='deepseek')`);
	d1Query(`INSERT INTO feeds(feed,source,next_poll_at) VALUES ('https://retired-private-marker.test/old','cisco',1)`);
	d1Query(`INSERT INTO ingest_runs(started_at,finished_at,polled,failed_feeds,anomalous_feeds) VALUES (${now - 1000},${now - 50},3,0,0),(${now - 100},NULL,0,0,0)`);
});
test('owner sees current feed issues and incomplete heartbeat while anonymous visitors see only deployment', async ({ page, request }, testInfo) => {
	await page.goto('/signup');
	await page.getByLabel('Email').fill('connor@couetil.com');
	await page.getByLabel('Password').fill('correct-horse-battery');
	await page.getByRole('button', { name: 'Create account' }).click();
	await page.waitForURL('**/');
	await page.getByRole('link', { name: 'Feed health', exact: false }).click();
	await expect(page).toHaveURL(/\/status\/?$/);
	const health = page.getByRole('region', { name: 'Ingestion health' });
	await expect(health).toBeVisible();
	await expect(health).toContainText(`${SOURCES.length} active feeds`);
	await expect(health).toContainText('Checking feeds');
	const failing = page.locator('[data-feed-health="openai"]');
	await expect(failing).toContainText('Failing');
	await expect(failing).toContainText('3 consecutive failed checks');
	await expect(failing).toContainText('503');
	await expect(failing).toContainText('upstream-private-marker');
	await expect(page.locator('[data-feed-health="meta-ai"]')).toContainText('Check parser');
	await expect(page.locator('[data-feed-health="deepseek"]')).toContainText('Not checked yet');
	await expect(health).toContainText('Retired endpoints (1)');
	await expect(health).not.toContainText('Overdue');
	await page.goto('/status');
	await expect(health).toBeVisible();
	await page.screenshot({ path: testInfo.outputPath('owner-health-phone.png'), fullPage: true });
	await page.setViewportSize({ width: 1280, height: 900 });
	await page.screenshot({ path: testInfo.outputPath('owner-health-desktop.png'), fullPage: true });
	const privateResponse = await page.request.get('/status');
	expect(privateResponse.headers()['cache-control']).toBe('private, no-store');
	expect(privateResponse.headers()['vary']).toBe('Cookie');
	const publicResponse = await request.get('/status');
	expect(publicResponse.status()).toBe(200);
	const html = await publicResponse.text();
	expect(html).toContain('Deployment');
	expect(html).not.toContain('upstream-private-marker');
	expect(html).not.toContain('retired-private-marker');
	expect(html).not.toContain('data-ingestion-health');
	expect(html).not.toContain('Last successful check');
	expect(publicResponse.headers()['cache-control']).toBe('private, no-store');
	d1Query(`UPDATE ingest_runs SET finished_at=${Math.floor(Date.now() / 1000)},polled=3,failed_feeds=1,anomalous_feeds=1 WHERE id=(SELECT MAX(id) FROM ingest_runs)`);
	await page.reload();
	await expect(health).toContainText('Completed with feed issues');
	await expect(health).toContainText('1 failed checks; 1 parsing anomalies');
	await page.getByRole('link', { name: 'Back to feed', exact: false }).click();
	await expect(page).toHaveURL(/\/$/);
});
