import { test, expect } from './fixtures';
import { d1Query } from './d1';
// Red -> green: the expanded source grid and history push the first story below
// the phone viewport, and the old read button measures only 16 by 16 pixels.
test.use({ viewport: { width: 390, height: 844 } });
test('compact controls keep the feed reachable and preserve keyboard multi-select', async ({ page }) => {
	const sources = ['cloudflare-blog', 'ieee-spectrum', 'apple', 'science-daily', 'amd', 'qualcomm', 'intel', 'nvidia', 'elonlit', 'anthropic', 'aws', 'cisco', 'ti', 'eye-on-the-market', 'mistral', 'openai', 'thinking-machines', 'meta-ai', 'owenomics', 'open-models', 'deepseek', 'cursor'];
	d1Query(`INSERT INTO items(source,guid,url,title,fetched_at) VALUES ${sources.map((source, i) => `('${source}','mobile-${i}','https://example.com/mobile-${i}','A useful update from ${source}',${1000 + i})`).join(',')}`);
	await page.goto('/signup');
	await page.getByLabel('Email').fill('connor@couetil.com');
	await page.getByLabel('Password').fill('correct-horse-battery');
	await page.getByRole('button', { name: 'Create account' }).click();
	await page.waitForURL('**/');
	d1Query(`INSERT INTO item_reads(user_id,item_id,read_at,opened_at) SELECT u.id,i.id,100,100 FROM users u CROSS JOIN items i WHERE i.source IN ('apple','meta-ai','cloudflare-blog')`);
	await page.goto('/');
	const first = page.locator('[data-feed-list] [data-feed-row]').first();
	expect((await first.boundingBox())!.y).toBeLessThan(520);
	const read = first.getByRole('button', { name: 'Mark as read', exact: true });
	const hitbox = (await read.boundingBox())!;
	expect(hitbox.width).toBeGreaterThanOrEqual(44);
	expect(hitbox.height).toBeGreaterThanOrEqual(44);
	const headline = (await first.locator('a').boundingBox())!;
	expect(hitbox.x).toBeGreaterThanOrEqual(headline.x + headline.width);
	await expect(first.locator('.read-square')).toHaveCSS('width', '16px');
	const sourceDetails = page.locator('.source-filter');
	const summary = sourceDetails.locator('summary');
	await expect(summary).toContainText('All sources');
	await summary.focus();
	await page.keyboard.press('Enter');
	await expect(sourceDetails).toHaveAttribute('open', '');
	const nav = page.getByRole('navigation', { name: 'Filter by source' });
	await nav.getByRole('link', { name: 'OpenAI', exact: true }).click();
	await expect(page).toHaveURL(/source=openai/);
	await expect(summary).toContainText('OpenAI');
	await summary.click();
	await nav.getByRole('link', { name: 'Texas Instruments', exact: true }).click();
	await expect(page).toHaveURL(/source=openai&source=ti/);
	await expect(summary).toContainText('OpenAI, Texas Instruments');
	await summary.click();
	await expect(nav.getByRole('link', { name: 'Texas Instruments', exact: true })).toHaveAttribute('aria-current', 'true');
	await page.getByRole('link', { name: 'Clear sources', exact: true }).click();
	await expect(page).toHaveURL(/\/$/);
	await expect(summary).toContainText('All sources');
	const recent = page.locator('[data-recently-viewed] details');
	await expect(recent).not.toHaveAttribute('open', '');
	await recent.locator('summary').focus();
	await page.keyboard.press('Enter');
	await expect(recent).toHaveAttribute('open', '');
	await expect(recent.getByRole('button', { name: 'Mark as unread' })).toHaveCount(3);
	await page.setViewportSize({ width: 1280, height: 900 });
	expect((await page.locator('[data-feed-list]').boundingBox())!.width).toBe(672);
	await expect(nav).toBeVisible();
});
